language: c
addons:
  apt:
    packages:
    - libncurses-dev
    - linux-headers-4.15.0-58-generic
    - libnuma-dev

cache:
  directories:
    - $HOME/dpdk

before_install:
  - >
    [ -z "$(ls -A $HOME/dpdk)" ] &&
    cd $HOME/dpdk &&
    wget http://fast.dpdk.org/rel/dpdk-18.11.5.tar.xz &&
    tar --strip-components=1 -axvf dpdk-18.11.5.tar.xz &&
    export RTE_KERNELDIR=/lib/modules/4.15.0-58-generic/build &&
    make install T=x86_64-native-linuxapp-gcc; true

script:
  - cd $TRAVIS_BUILD_DIR
  - export RTE_SDK=$HOME/dpdk
  - export RTE_TARGET=x86_64-native-linuxapp-gcc
  - make

